[package]
name = "lunar-chess"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
fast_image_resize = { version = "5.3", features = ["image", "rayon"] }
font-kit = "0.14.3"
image = "0.25.8"
ndarray = "0.16.1"
ort = { version = "=2.0.0-rc.10", features = ["cuda"] }
raqote = "0.8.5"
ruci = { version = "2.1.0", features = ["engine-async", "tokio-process"] }
shakmaty = "0.29.4"
softbuffer = "0.4"
tokio = { version = "1.48.0", features = [
	"macros",
	"rt-multi-thread",
	"process",
] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
winit = "0.30"
xcap = "0.7"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = [
	"Win32_Foundation",
	"Win32_UI_WindowsAndMessaging",
] }
