[engine]
# path = "models/chessbots/lc0.exe"
# args = ["--weights=models/chessbots/maia-1100.pb.gz"]
path = "models/chessbots/stockfish.exe"
args = []
threads = 6
hash = 256
multi_pv = 3
move_time = 1000

[detection]
# piece_path = "models/piece.onnx"

[debugging]
level = "debug"
show_grid = true
show_piece_labels = true
