[engine]
path = "models/chessbots/lc0.exe"
args = ["--weights=models/chessbots/maia-1900.pb.gz"]
profile = "default"

[profiles.default]
threads = 8
hash = 8192
multi_pv = 6
depth = 5

[detection]
path = "models/piece.onnx"
piece_confidence_threshold = 0.75

[debugging]
level = "debug"
stream_proof = true
show_grid = true
show_piece_labels = true
