[engine]
path = "" # Path to the exe of the engine
args = [] # Any args you give the engine like '--weights='
book = "" # Optional: Path to a .bin polyglot opening book
profile = "default" # The profile to use from [profiles.<name>]

# Profiles to change the UCI options and go
[profiles.default]
# UCI options are passed directly to the engine via "setoption"
# See https://backscattering.de/chess/uci/#engine-option for standard options
uci.Threads = "8"
uci.Hash = "8192"
uci.MultiPV = "6"

# Go commands control the search parameters
# See https://backscattering.de/chess/uci/#gui-go for available commands
go.depth = 5

[detection]
path = "" # Path to the ONNX file that detect the pieces
piece_confidence_threshold = 0.75 # Threshold to show the pieces based on its confidence

[debugging]
level = "info" # Level to show the logs: info, debug, warn, error, trace
stream_proof = true # Whether to show the overlay on screen
show_grid = false # Shows the detected grid
show_piece_labels = false # Shows which pieces are labeled what
