[engine]
path = "" # Path to the exe of the engine
args = [] # Any args you give the engine like '--weights='
profile = "default" # The profile to use from [profiles.<name>]

# Profiles to change the UCI options and go
[profiles.default]
threads = 8
hash = 8192
multi_pv = 6
depth = 5

[detection]
path = "" # Path to the ONNX file that detect the pieces
piece_confidence_threshold = 0.75 # Threshold to show the pieces based on its confidence

[debugging]
level = "info" # Level to show the logs: info, debug, warn, error, trace
stream_proof = true # Whether to show the overlay on screen
show_grid = false # Shows the detected grid
show_piece_labels = false # Shows which pieces are labeled what
